# https://github.com/realm/SwiftLint#configuration
disabled_rules: # デフォルトで有効なルールのうち、無効にしたいもの
- block_based_kvo
- control_statement
- cyclomatic_complexity
- deployment_target
- duplicate_enum_cases
- empty_enum_arguments
- file_length
- for_where
- function_parameter_count
- generic_type_name
- implicit_getter
- large_tuple
- leading_whitespace
- legacy_hashing
- nesting
- no_fallthrough_only
- private_over_fileprivate
- unneeded_break_in_switch
- unused_capture_list
- unused_closure_parameter
- unused_control_flow_label
- unused_enumerated
- unused_setter_value
- xctfail_message


opt_in_rules: # デフォルトで無効のルールのうち、有効にしたいもの
- anyobject_protocol
- closure_end_indentation
- closure_spacing
- collection_alignment
- empty_collection_literal
- empty_string
- fatal_error_message
- first_where
- flatmap_over_map_reduce
- force_unwrapping
- identical_operands
- indentation_width
- literal_expression_end_indentation
- modifier_order
- multiline_arguments
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- multiline_parameters_brackets
- operator_usage_whitespace
- overridden_super_call
- prefer_zero_over_explicit_init
- private_action
- private_outlet
- redundant_nil_coalescing
- sorted_imports
- strong_iboutlet
- switch_case_on_newline
- toggle_bool
- trailing_closure
- unowned_variable_capture
- vertical_parameter_alignment_on_call
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces



excluded:
- Pods/

# 変数名の最低文字数
identifier_name:
  min_length: 3
